### ISSUE TITLE
Tensorflow dependency

### ISSUE THREAD

**Issue by GJBoth** [j3soon/tbparse#10]
Thanks for this very useful package! It helps me a lot in several projects and I'd like to use it for several others, but a very big downside is the dependency on tensorflow. Looking at the code, it seems to be only used very sparingly, and it would be amazing if tensorflow would no longer need to be a dependency, or an optional dependency otherwise.

**Comment by j3soon** [comment]
The TensorFlow dependency is intentional since we aim to reuse the parsing logic in TensorFlow/TensorBoard. (less error-prone, especially for images and audio)

If your training code uses a different version of TensorFlow, you can isolate your parsing/plotting code in another virtual environment to avoid dependency conflict.

I wonder if you have any special use case that must not use TensorFlow as a dependency?

**Comment by GJBoth** [comment]
Thanks for your quick answer! While we *could* include tensorflow as a dependency, IMO keeping dependencies to a minimum is good practice. In this case especially, since tensorflow is huge! Using pytorch (or jax, ...) but then having to install the entirety of tensorflow just for parsing of logs is quite undesirable and not something I can sell to my team..,.

**Comment by j3soon** [comment]
I got your point, I overlooked the size of the `tensorflow` package. (since it's cached on my machine)

I agree that `tensorflow` is huge ([400+MBs](https://pypi.org/project/tensorflow/#files)), and so is the `tensorflow-cpu` package ([200+MBs](https://pypi.org/project/tensorflow-cpu/#files)). Moreover, there [isn't a simple way to only depend on](https://github.com/tensorflow/tensorflow/issues/7166) either `tensorflow` or `tensorflow-cpu`, which means that if `tensorflow-cpu` is already installed, the `tensorflow` package will still be downloaded.

As you have mentioned, the best solution is to remove all TensorFlow operations and only depend on `tensorboard` ([5.8 MBs](https://pypi.org/project/tensorboard/#files)), or make TensorFlow an optional dependency when parsing images and audio.

Removing all TensorFlow operations isn't a trivial task, and may not be preferred when supporting more event types in the future. Maybe it's better to make TensorFlow an optional dependency, which only requires modifying [this line](https://github.com/j3soon/tbparse/blob/4bd87404040fd85bdd72b89fefd21e9c6486d26a/tbparse/summary_reader.py#L776).

I may try to implement this during my free time (hopefully within a few weeks). Meanwhile, you may need to put up with the large size of TensorFlow.

**Comment by j3soon** [comment]
This issue is resolved in 0804837713a1e2052ec77887bac1d385dca5fef0, and fixed in the latest release ([v0.0.7](https://github.com/j3soon/tbparse/releases/tag/v0.0.7)) on [PyPI](https://pypi.org/project/tbparse/).

Please follow the following document for using tbparse without TensorFlow:

https://tbparse.readthedocs.io/en/latest/pages/installation.html#tbparse-installing-without-tensorflow

**Comment by GJBoth** [comment]
Thanks, this is very helpful!
